//! Shell integration — OSC 133 without editing a line of anyone's rc files.
//!
//! Every shell already offers a route in that does not involve modifying the
//! user's configuration, and Mica takes it:
//!
//! | Shell | Route |
//! |---|---|
//! | zsh | a generated `ZDOTDIR` whose `.zshrc` sources ours and then chains to the user's |
//! | bash | `BASH_ENV`, which bash sources before an interactive rc |
//! | fish | `XDG_DATA_DIRS`, whose `vendor_conf.d` fish sources automatically |
//!
//! Two rules run through all of it:
//!
//! - **Everything is written to a temporary directory owned by this process.**
//!   Nothing under `$HOME` is ever opened for writing. The test below asserts
//!   that the user's real rc files are byte-identical before and after.
//! - **Chain, never replace.** If the user already has a `zle-line-pre-redraw`
//!   widget or a `fish_prompt`, Mica's version calls theirs. Replacing it would
//!   silently break a configuration the user spent years on, and they would
//!   have no way to tell it was us.

use std::io;
use std::path::{Path, PathBuf};

/// Which shell a session is running.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shell {
    Zsh,
    Bash,
    Fish,
    /// Anything else. Integration is skipped; the terminal still works, it just
    /// has no command blocks.
    Other,
}

impl Shell {
    /// Identifies a shell from its path.
    pub fn detect(program: &Path) -> Shell {
        match program.file_name().and_then(|n| n.to_str()) {
            Some("zsh") => Shell::Zsh,
            Some("bash" | "sh") => Shell::Bash,
            Some("fish") => Shell::Fish,
            _ => Shell::Other,
        }
    }

    pub fn supports_blocks(self) -> bool {
        !matches!(self, Shell::Other)
    }
}

/// The generated integration directory, plus the environment it implies.
#[derive(Debug, Clone)]
pub struct Integration {
    root: PathBuf,
    /// `(name, value)` pairs to add to the child's environment.
    env: Vec<(String, String)>,
}

impl Integration {
    pub fn root(&self) -> &Path {
        &self.root
    }

    pub fn env(&self) -> &[(String, String)] {
        &self.env
    }
}

/// Writes the integration for `shell` into `root`.
///
/// `root` must be a directory this process owns — a per-session temporary
/// directory, never anything under the user's configuration.
pub fn generate(shell: Shell, root: &Path) -> io::Result<Integration> {
    std::fs::create_dir_all(root)?;
    let mut env = Vec::new();

    match shell {
        Shell::Zsh => {
            // The user's real ZDOTDIR, so our generated .zshrc can chain to it.
            // `$HOME` is the default when it is unset, which is what zsh does.
            let user_zdotdir = std::env::var("ZDOTDIR")
                .ok()
                .filter(|s| !s.is_empty())
                .or_else(|| std::env::var("HOME").ok())
                .unwrap_or_default();

            std::fs::write(root.join("mica.zsh"), ZSH_INTEGRATION)?;
            std::fs::write(root.join(".zshrc"), zsh_rc(root))?;
            // zsh reads .zshenv from ZDOTDIR too; chaining it keeps a user's
            // PATH setup working.
            std::fs::write(root.join(".zshenv"), zsh_env())?;

            env.push(("MICA_USER_ZDOTDIR".into(), user_zdotdir));
            env.push(("ZDOTDIR".into(), root.display().to_string()));
        }
        Shell::Bash => {
            let path = root.join("mica.bash");
            std::fs::write(&path, BASH_INTEGRATION)?;
            env.push(("BASH_ENV".into(), path.display().to_string()));
        }
        Shell::Fish => {
            // fish sources `vendor_conf.d/*.fish` from every entry in
            // XDG_DATA_DIRS. No config file is touched and no directory of the
            // user's is written to.
            let conf_dir = root.join("fish").join("vendor_conf.d");
            std::fs::create_dir_all(&conf_dir)?;
            std::fs::write(conf_dir.join("mica.fish"), FISH_INTEGRATION)?;

            let existing = std::env::var("XDG_DATA_DIRS").unwrap_or_default();
            let combined = if existing.is_empty() {
                root.display().to_string()
            } else {
                format!("{}:{existing}", root.display())
            };
            env.push(("XDG_DATA_DIRS".into(), combined));
        }
        Shell::Other => {}
    }

    if shell.supports_blocks() {
        env.push(("MICA_SHELL_INTEGRATION".into(), "1".into()));
    }
    Ok(Integration { root: root.to_path_buf(), env })
}

/// The generated `.zshrc`: source ours, then hand control to the user's.
///
/// Ours goes **first** so that a user's `precmd` can see the markers already
/// registered, and so a `.zshrc` that calls `exec` still gets our integration.
fn zsh_rc(root: &Path) -> String {
    format!(
        r#"# Generated by Mica. This file lives in a temporary directory and is
# deleted when the session ends. Your own ~/.zshrc is never modified.
source {root}/mica.zsh

# Hand control back to the user's configuration.
ZDOTDIR="${{MICA_USER_ZDOTDIR:-$HOME}}"
[[ -f "$ZDOTDIR/.zshrc" ]] && source "$ZDOTDIR/.zshrc"
"#,
        root = root.display()
    )
}

fn zsh_env() -> String {
    r#"# Generated by Mica. Chains to the user's .zshenv and nothing more.
[[ -n "${MICA_USER_ZDOTDIR-}" && -f "$MICA_USER_ZDOTDIR/.zshenv" ]] \
    && source "$MICA_USER_ZDOTDIR/.zshenv"
"#
    .to_owned()
}

/// zsh: `add-zle-hook-widget` for the line editor, `precmd`/`preexec` for the
/// command boundaries.
///
/// The chaining is the delicate part. `add-zle-hook-widget` already composes,
/// but a user who set `zle -N zle-line-pre-redraw` directly did not go through
/// it, so the previous widget is captured and called explicitly.
const ZSH_INTEGRATION: &str = r#"# Mica shell integration (zsh).
# Emits OSC 133 semantic prompt markers. Sourced from a generated ZDOTDIR;
# your own configuration is never modified.

[[ -o interactive ]] || return 0
[[ -n "${MICA_INTEGRATION_LOADED-}" ]] && return 0
typeset -g MICA_INTEGRATION_LOADED=1

_mica_osc() { printf '\033]%s\007' "$1" }

# OSC 7: report the working directory so new tabs open in the right place.
_mica_report_cwd() {
    local encoded="${PWD//\%/%25}"
    encoded="${encoded// /%20}"
    _mica_osc "7;file://${HOST}${encoded}"
}

_mica_precmd() {
    local exit_status=$?
    # D closes the previous command. On the very first prompt there is nothing
    # to close, which is why the guard is a flag rather than a status check.
    if [[ -n "${_mica_command_running-}" ]]; then
        _mica_osc "133;D;${exit_status}"
        unset _mica_command_running
    fi
    _mica_report_cwd
    _mica_osc "133;A"
}

_mica_preexec() {
    typeset -g _mica_command_running=1
    # Report the command line itself so a block can be labelled without the
    # terminal having to scrape it back out of the grid.
    _mica_osc "133;C;cmd=${1}"
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd _mica_precmd
add-zsh-hook preexec _mica_preexec

# B marks the end of the prompt and the start of user input.
_mica_line_init() {
    _mica_osc "133;B"
    # Chain: a widget the user installed directly still has to fire.
    [[ -n "${_mica_prev_line_init-}" ]] && zle "$_mica_prev_line_init" -- "$@"
}

if autoload -Uz add-zle-hook-widget 2>/dev/null; then
    typeset -g _mica_prev_line_init="${widgets[zle-line-init]#user:}"
    add-zle-hook-widget line-init _mica_line_init
fi
"#;

/// bash: `BASH_ENV` is read before the interactive rc, so the traps are in
/// place by the time anything the user configured runs.
const BASH_INTEGRATION: &str = r#"# Mica shell integration (bash).
# Loaded via BASH_ENV. Your ~/.bashrc and ~/.bash_profile are never modified.

case $- in *i*) ;; *) return 0 ;; esac
[[ -n "${MICA_INTEGRATION_LOADED-}" ]] && return 0
MICA_INTEGRATION_LOADED=1

_mica_osc() { printf '\033]%s\007' "$1"; }

_mica_report_cwd() {
    local encoded="${PWD// /%20}"
    _mica_osc "7;file://${HOSTNAME}${encoded}"
}

_mica_prompt() {
    local exit_status=$?
    if [[ -n "${_mica_command_running-}" ]]; then
        _mica_osc "133;D;${exit_status}"
        unset _mica_command_running
    fi
    _mica_report_cwd
    _mica_osc "133;A"
    return $exit_status
}

_mica_preexec() {
    # DEBUG fires for every command in a compound statement; only the first
    # one is the command the user actually ran.
    [[ -n "${_mica_command_running-}" ]] && return
    [[ "$BASH_COMMAND" == "_mica_prompt"* ]] && return
    _mica_command_running=1
    _mica_osc "133;C;cmd=${BASH_COMMAND}"
}

# Chain rather than replace: appending to PROMPT_COMMAND preserves whatever
# the user already had there.
if [[ "${PROMPT_COMMAND-}" != *_mica_prompt* ]]; then
    PROMPT_COMMAND="_mica_prompt${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi
trap '_mica_preexec' DEBUG

# B goes at the end of the prompt string itself, which is the only place bash
# lets us mark the boundary between prompt and input.
PS1='\[\033]133;B\007\]'"${PS1-}"
"#;

/// fish: copy the user's `fish_prompt` aside and wrap it.
///
/// fish has no `PS1` to append to, so the prompt function itself has to be
/// wrapped — and copying it first is what makes that a wrap rather than a
/// replacement.
const FISH_INTEGRATION: &str = r#"# Mica shell integration (fish).
# Loaded from vendor_conf.d. Your config.fish is never modified.

status is-interactive; or exit 0
set -q MICA_INTEGRATION_LOADED; and exit 0
set -g MICA_INTEGRATION_LOADED 1

function _mica_osc
    printf '\033]%s\007' $argv[1]
end

function _mica_report_cwd
    _mica_osc "7;file://$hostname$PWD"
end

# Copy the user's prompt aside so ours can call it rather than replace it.
if functions -q fish_prompt
    functions -c fish_prompt _mica_user_fish_prompt

    function fish_prompt
        _mica_osc "133;A"
        _mica_report_cwd
        _mica_user_fish_prompt
        _mica_osc "133;B"
    end
end

function _mica_preexec --on-event fish_preexec
    _mica_osc "133;C;cmd=$argv[1]"
end

function _mica_postexec --on-event fish_postexec
    _mica_osc "133;D;$status"
end
"#;

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir()
            .join(format!("mica-integration-{}-{name}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        dir
    }

    #[test]
    fn shells_are_detected_from_their_path() {
        assert_eq!(Shell::detect(Path::new("/bin/zsh")), Shell::Zsh);
        assert_eq!(Shell::detect(Path::new("/opt/homebrew/bin/fish")), Shell::Fish);
        assert_eq!(Shell::detect(Path::new("/bin/bash")), Shell::Bash);
        assert_eq!(Shell::detect(Path::new("/usr/local/bin/nu")), Shell::Other);
    }

    #[test]
    fn an_unknown_shell_still_gets_a_terminal_just_without_blocks() {
        let dir = temp_dir("other");
        let integration = generate(Shell::Other, &dir).unwrap();
        assert!(integration.env().is_empty(), "an unknown shell must not get env changes");
        assert!(!Shell::Other.supports_blocks());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn zsh_gets_a_generated_zdotdir_that_chains_to_the_users_own() {
        let dir = temp_dir("zsh");
        let integration = generate(Shell::Zsh, &dir).unwrap();

        let names: Vec<&str> = integration.env().iter().map(|(k, _)| k.as_str()).collect();
        assert!(names.contains(&"ZDOTDIR"));
        assert!(names.contains(&"MICA_USER_ZDOTDIR"));

        let rc = std::fs::read_to_string(dir.join(".zshrc")).unwrap();
        assert!(rc.contains("source"), "the generated rc does not source anything");
        assert!(
            rc.contains("MICA_USER_ZDOTDIR"),
            "the generated rc does not chain to the user's:\n{rc}"
        );
        assert!(dir.join("mica.zsh").exists());
        assert!(dir.join(".zshenv").exists(), "a user's .zshenv would be skipped");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn the_zsh_integration_chains_rather_than_replacing_a_widget() {
        // A user who set `zle -N zle-line-init` directly must still have their
        // widget fire. Replacing it would break a configuration silently.
        assert!(ZSH_INTEGRATION.contains("_mica_prev_line_init"));
        assert!(
            ZSH_INTEGRATION.contains(r#"zle "$_mica_prev_line_init""#),
            "the previous widget is captured but never called"
        );
    }

    #[test]
    fn bash_is_loaded_through_bash_env_and_appends_to_prompt_command() {
        let dir = temp_dir("bash");
        let integration = generate(Shell::Bash, &dir).unwrap();
        assert_eq!(integration.env()[0].0, "BASH_ENV");
        assert!(dir.join("mica.bash").exists());
        // Assigning PROMPT_COMMAND outright would discard whatever the user
        // had there — which for many people is their entire prompt.
        assert!(BASH_INTEGRATION.contains(r#"PROMPT_COMMAND="_mica_prompt${PROMPT_COMMAND:+;$PROMPT_COMMAND}""#));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn fish_is_loaded_through_vendor_conf_d_and_wraps_the_users_prompt() {
        let dir = temp_dir("fish");
        let integration = generate(Shell::Fish, &dir).unwrap();
        assert_eq!(integration.env()[0].0, "XDG_DATA_DIRS");
        assert!(dir.join("fish/vendor_conf.d/mica.fish").exists());
        assert!(
            FISH_INTEGRATION.contains("functions -c fish_prompt _mica_user_fish_prompt"),
            "fish's prompt is replaced rather than wrapped"
        );
        assert!(FISH_INTEGRATION.contains("_mica_user_fish_prompt\n"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn fish_preserves_an_existing_xdg_data_dirs() {
        // Prepending is fine; overwriting would hide every other vendor's
        // fish completions on the machine.
        let existing = std::env::var("XDG_DATA_DIRS").unwrap_or_default();
        let dir = temp_dir("fish-xdg");
        let integration = generate(Shell::Fish, &dir).unwrap();
        let value = &integration.env()[0].1;
        assert!(value.starts_with(&dir.display().to_string()));
        if !existing.is_empty() {
            assert!(value.ends_with(&existing), "the existing XDG_DATA_DIRS was dropped");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn every_shell_emits_the_full_osc133_set() {
        for (shell, script) in [
            ("zsh", ZSH_INTEGRATION),
            ("bash", BASH_INTEGRATION),
            ("fish", FISH_INTEGRATION),
        ] {
            for marker in ["133;A", "133;B", "133;C", "133;D"] {
                assert!(script.contains(marker), "{shell} never emits {marker}");
            }
            assert!(script.contains("7;file://"), "{shell} never reports its cwd");
        }
    }

    #[test]
    fn every_shell_guards_against_being_loaded_twice() {
        // A nested shell, or a `source ~/.zshrc`, would otherwise register the
        // hooks again and emit every marker twice.
        for script in [ZSH_INTEGRATION, BASH_INTEGRATION, FISH_INTEGRATION] {
            assert!(script.contains("MICA_INTEGRATION_LOADED"));
        }
    }

    #[test]
    fn every_shell_does_nothing_in_a_non_interactive_session() {
        // A script run with `zsh -c` must not get prompt markers in its stdout.
        assert!(ZSH_INTEGRATION.contains("[[ -o interactive ]] || return 0"));
        assert!(BASH_INTEGRATION.contains("case $- in *i*)"));
        assert!(FISH_INTEGRATION.contains("status is-interactive"));
    }

    #[test]
    fn nothing_is_ever_written_outside_the_generated_directory() {
        // The claim that makes "never edits your rc files" true. Every path
        // the generator produces has to be inside the directory it was given.
        for shell in [Shell::Zsh, Shell::Bash, Shell::Fish] {
            let dir = temp_dir(&format!("contained-{shell:?}"));
            generate(shell, &dir).unwrap();

            let mut stack = vec![dir.clone()];
            let mut seen = 0;
            while let Some(path) = stack.pop() {
                for entry in std::fs::read_dir(&path).unwrap() {
                    let entry = entry.unwrap().path();
                    assert!(
                        entry.starts_with(&dir),
                        "{shell:?} wrote outside its directory: {}",
                        entry.display()
                    );
                    if entry.is_dir() {
                        stack.push(entry);
                    } else {
                        seen += 1;
                    }
                }
            }
            assert!(seen > 0, "{shell:?} generated no files at all");
            let _ = std::fs::remove_dir_all(&dir);
        }
    }

    #[test]
    fn the_users_real_dotfiles_are_untouched() {
        // The Phase 7 exit test, stated directly: read the user's own rc files
        // before and after generating integration for all three shells, and
        // require them to be byte-identical.
        let home = PathBuf::from(std::env::var("HOME").unwrap_or_default());
        let watched = [
            home.join(".zshrc"),
            home.join(".zshenv"),
            home.join(".bashrc"),
            home.join(".bash_profile"),
            home.join(".config/fish/config.fish"),
        ];
        let before: Vec<Option<Vec<u8>>> =
            watched.iter().map(|p| std::fs::read(p).ok()).collect();

        for shell in [Shell::Zsh, Shell::Bash, Shell::Fish] {
            let dir = temp_dir(&format!("dotfiles-{shell:?}"));
            generate(shell, &dir).unwrap();
            let _ = std::fs::remove_dir_all(&dir);
        }

        let after: Vec<Option<Vec<u8>>> =
            watched.iter().map(|p| std::fs::read(p).ok()).collect();
        for (i, path) in watched.iter().enumerate() {
            assert_eq!(
                before[i],
                after[i],
                "Mica modified {} — the central promise is broken",
                path.display()
            );
        }
    }
}
