//! The terminal-emulation boundary.
//!
//! Mica does not own a VT parser. It owns a *trait* that a VT parser can be
//! plugged into, and two implementations of it:
//!
//! - [`ghostty::GhosttyCore`] — libghostty-vt, the primary target. Its Unicode,
//!   grapheme, reflow, and Kitty-protocol handling is ahead of anything
//!   Rust-native, and its `render_state` dirty-row API exists precisely so that
//!   callers can bring their own renderer.
//! - [`alacritty::AlacrittyCore`] — a pure-Rust fallback that must stay green.
//!
//! The trait exists because libghostty-vt has never been tagged with a
//! version, warns in its own header that breaking changes are expected, and
//! drags Zig into the build. One day of trait now buys survivability against
//! all three.
//!
//! ## The one rule
//!
//! **There is no `full_grid()` method, and there must never be one.** The
//! moment it exists something will call it every frame, and the
//! zero-command-buffers-when-idle property dies quietly and unnoticeably. A
//! renderer that needs everything calls [`TerminalCore::damage_all`] and then
//! iterates [`TerminalCore::dirty_rows`] like everybody else.

pub mod mirror;

#[cfg(feature = "alacritty")]
pub mod alacritty;
#[cfg(feature = "ghostty")]
pub mod ghostty;

use crate::cell::Cell;
use crate::semantic::SemanticEvent;
use crate::sidetable::SideTables;

/// A position in the scrollback-extended coordinate space.
///
/// `line` is relative to the top of the viewport: `0` is the first visible
/// row, negatives reach up into scrollback.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Default)]
pub struct Point {
    pub line: i32,
    pub column: u16,
}

impl Point {
    pub const fn new(line: i32, column: u16) -> Point {
        Point { line, column }
    }
}

/// One row that changed since the last [`TerminalCore::clear_damage`].
#[derive(Debug, Clone, Copy)]
pub struct RowRef<'a> {
    /// Viewport row index, `0` at the top.
    pub index: u16,
    pub cells: &'a [Cell],
    /// The row wrapped rather than ended — the renderer needs this to avoid
    /// drawing a spurious line break, and reflow needs it on resize.
    pub wrapped: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CursorShape {
    #[default]
    Block,
    Underline,
    Bar,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CursorState {
    pub line: u16,
    pub column: u16,
    pub shape: CursorShape,
    pub visible: bool,
    pub blinking: bool,
}

impl Default for CursorState {
    fn default() -> CursorState {
        CursorState {
            line: 0,
            column: 0,
            shape: CursorShape::Block,
            visible: true,
            blinking: true,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Selection {
    pub start: Point,
    pub end: Point,
    pub rectangular: bool,
}

/// What a renderer needs from a terminal, and nothing more.
///
/// Deliberately not object-safe: there is exactly one backend per build, chosen
/// by a feature flag, and monomorphising it keeps the hot path free of virtual
/// dispatch.
pub trait TerminalCore: Sized {
    fn new(cols: u16, rows: u16, scrollback: u32) -> Self;

    /// Feed bytes read from the PTY.
    fn write(&mut self, bytes: &[u8]);

    fn resize(&mut self, cols: u16, rows: u16);

    /// Move the viewport within scrollback. Positive scrolls toward history.
    fn scroll_viewport(&mut self, delta: i32);

    fn dimensions(&self) -> (u16, u16);

    /// Rows that changed since the last [`Self::clear_damage`].
    ///
    /// This is the load-bearing method of the whole architecture. If it yields
    /// nothing, the renderer submits nothing.
    fn dirty_rows(&self) -> impl Iterator<Item = RowRef<'_>>;

    /// Cheap predicate for the frame scheduler, so it can decide not to render
    /// without building an iterator.
    fn has_damage(&self) -> bool;

    /// Mark every visible row dirty. The escape hatch for resize, theme
    /// cross-fade, and font change — an explicit, greppable call site rather
    /// than an innocuous-looking `full_grid()` that creeps into the frame loop.
    fn damage_all(&mut self);

    fn clear_damage(&mut self);

    fn cursor(&self) -> CursorState;

    fn selection(&self) -> Option<Selection>;
    fn set_selection(&mut self, selection: Option<Selection>);

    /// Text of the current selection, for the clipboard.
    fn selection_text(&self) -> Option<String>;

    /// OSC 133 / OSC 7 / OSC 9 events since the last drain.
    fn drain_semantic_events(&mut self) -> Vec<SemanticEvent>;

    /// Bytes the terminal owes the child process — DA1 and DSR replies, and
    /// anything else generated by parsing rather than by the user. The session
    /// loop drains this straight into the PTY.
    fn take_replies(&mut self) -> Vec<u8>;

    fn side_tables(&self) -> &SideTables;

    /// Total rows held, including scrollback — for the scrollbar, not for
    /// rendering.
    fn history_len(&self) -> usize;

    /// A window title set via OSC 0/2, if it changed since the last call.
    fn take_title(&mut self) -> Option<String>;
}

/// The backend this build selected, so callers can name one type.
#[cfg(all(feature = "ghostty", not(feature = "alacritty")))]
pub type Backend = ghostty::GhosttyCore;

#[cfg(feature = "alacritty")]
pub type Backend = alacritty::AlacrittyCore;

#[cfg(not(any(feature = "ghostty", feature = "alacritty")))]
compile_error!("mica-core needs exactly one terminal backend: enable `ghostty` or `alacritty`");
